//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeRepairApplication.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumeRecord
    {
        public long Id { get; set; }
        public int ResumePlatform { get; set; }
        public string ResumeId { get; set; }
        public Nullable<int> MatchPlatform { get; set; }
        public string MatchResumeId { get; set; }
        public Nullable<System.DateTime> MatchDate { get; set; }
        public Nullable<System.DateTime> DownLoadDate { get; set; }
        public int LibraryExist { get; set; }
        public int Status { get; set; }
        public string Email { get; set; }
        public string Cellphone { get; set; }
    }
}
